language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "usil-manuel"
script:
  - pytest
  - behave ./test_aceptance/
  - sonar-scanner